### ISSUE TITLE
'Return to event cart' not added to SPCO payment step initially but does with a refresh.

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/ee4-mer#11]
Reported here: https://eventespresso.com/topic/return-to-event-cart-button-missing-at-payment-checkout-page/#post-281040

This was also reproduced here: https://github.com/eventespresso/eea-paypal-smart-buttons/issues/25
However at the time only appeared to effect PayPal Smart Buttons, I didn't realised it wasn't loading initially.

## Issue Overview
If you have MER enabled, add some registrations to your cart, proceed through until you get to the payment options, the 'Return to cart' button is not within the page source - http://take.ms/L37ds

Refresh the page and the button appears - http://take.ms/ZV2QM

Using the latest master of EE core and MER.

**Comment by joshfeck** [comment]
https://eventespresso.com/topic/add-a-back-to-event-cart-from-registration-checkout-screen/

**Comment by joshfeck** [comment]
The button in question gets loaded in via the 
`FHEE__EE_SPCO_Reg_Step__reg_step_submit_button__sbmt_btn_html` (core) filter hook.

Screenshot of payment option step after initial load:
![Screen Shot 2020-02-20 at 2 07 11 PM](https://user-images.githubusercontent.com/891156/74969381-7d6d7700-53ea-11ea-90e3-44a221de551d.png)

then after refreshing the page:
![Screen Shot 2020-02-20 at 2 07 25 PM](https://user-images.githubusercontent.com/891156/74969412-88c0a280-53ea-11ea-8a1a-0578dadaa98e.png)
