### ISSUE TITLE
Make all Sub-Items of Ticket visible in event cart before registration

### ISSUE THREAD

**Issue by prafulkalpund** [eventespresso/ee4-mer#17]
## Issue Overview
We want to show all sub-items of a particular Ticket ( like price modifier discount ) from the event in event cart page before a user register.

## Bug report or feature request?
* [x] Feature

## Environment Data:

Version of EE core:  4.9.68.p

Version of this addon: 2.0.14.p (MER Version)

Version of WordPress:4.9

Browser used:  Chrome

## Expected Behaviour
All the sub-items of a ticket should be visible before a user register. 
Example: Price Modifier Discount or Promotion ( On a Specific ticket and not on overall cart )

## Current Behaviour
After registration user can see all the sub-items of tickets.

## Related Information:
As shown in below screenshots, Before Registration user is not able to see Early Bird Discount ( Price Modifier Discount ) as soon as user complete registation user get deatiled about Early Bird Discount for that ticket. 

![selection_036](https://user-images.githubusercontent.com/37687876/49715149-7c34ac00-fc75-11e8-8d16-b52507a3f3e3.png)
![selection_037](https://user-images.githubusercontent.com/37687876/49715147-7b9c1580-fc75-11e8-93c2-4884dbd1866c.png)

**Comment by joshfeck** [comment]
Hi,

This will require a few changes in the MER add-on, one of them being a new filter hook. I'll get a pull request started. If & when that pull request gets merged & included in an upcoming release of the MER add-on, you'll be able to use a filter function to "switch" on the display of the sub line items.

**Comment by joshfeck** [comment]
Yes, it does add much clutter. If you can come up with a better way to display those items, we'd love to see those ideas.

**Comment by prafulkalpund** [comment]
Hi Joshfeck,
I have made some core changes to make it user convenient. I am sharing its screenshot.
let me your thought on this.
![selection_043](https://user-images.githubusercontent.com/37687876/50435290-9a9dd700-0906-11e9-8e21-76f2436c0757.png)

Changes Made by me:
1. New extra column added as "Actual Price"
2. In Description, I have added all the subline items with their details on discount
3. Price column is renamed as "Discounted Price"  

This will also work will multiple events and multiple tickets.

**Comment by hreidco** [comment]
@joshfeck is there any likelyhood that EE will change the MER plugin to allow the display that @prafulkalpund has shared?

**Comment by hreidco** [comment]
@joshfeck the hooks are exactly what we need. Could you add them to the next MER update?

**Comment by hreidco** [comment]
@joshfeck is there any chance the hooks could be added to the next MER update? If so, any idea when that might be? If it is later than February 1st then we will just edit your plugin directly, but either way, it would be helpful to get an idea. Thanks!

**Comment by joshfeck** [comment]
Maybe what you could do is do a pull request that includes the hooks you need to do your customizations without hacking MER directly. Here's a link to the Event Espresso documentation that outlines naming conventions for hooks:

https://github.com/eventespresso/event-espresso-core/blob/master/docs/A--Best-Practices/ee-actions-and-filters.md#naming-convention-for-actions-and-filters-within-classes-or-functions

**Comment by prafulkalpund** [comment]
@joshfeck, We have added four filters in EE_Event_Cart_Line_Item_Display_Strategy.php file and It is working absolutely fine as per our requirement. Please find my attached file below, I tried to follow all the rules mentioned in naming convention for Actions and Filters within classes or functions documentetion.
Let us know if this change will ok for you.

Note: I am sharing a file with txt extension because I am not allowed to upload the Php file here. Please ignore this small change.
[EE_Event_Cart_Line_Item_Display_Strategy.txt](https://github.com/eventespresso/ee4-mer/files/2790396/EE_Event_Cart_Line_Item_Display_Strategy.txt)

**Comment by joshfeck** [comment]
Thanks. We will need to clean up the formatting since the additions do not follow coding standards. If you would have done [a pull request](https://help.github.com/articles/creating-a-pull-request/) you would not have had to resort to making a .txt file. 

We'll try to get to doing the pull request with the formatting cleanup when we can.

**Comment by joshfeck** [comment]
The hooks had some issues (in one case causing duplicated content), so the proposed hooks required some changes.

**Comment by joshfeck** [comment]
#20 has been merged
