### ISSUE TITLE
Account for required tickets in ticket selector so max limits are enforced

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/ee4-mer#2]
There are some unexpected shenanigans when a ticket is required and the View Event Cart button is clicked. What happens is the View Event Cart button submits the ticket selector form again and adds the required ticket to the cart again. 

Steps to replicate the issue:

1) Set up an event with a required ticket
2) Set the required ticket's Maximum Quantity field to 1
![Screen Shot 2020-02-20 at 2 16 53 PM](https://user-images.githubusercontent.com/891156/74970134-d8ec3480-53eb-11ea-8632-5381567def55.png)

3) Go to the front end and add the ticket to the cart
4) Close the modal and click the View Event Cart button

The unexpected result is an additional required ticket is added to the cart in step 4. This is particularly bad if the the required ticket has a maximum quantity limit of 1.

One possible solution may be to change the behavior of MER so that the View Event Cart button doesn't resubmit the ticket selector form and instead behaves more like a link to the cart page. Or possibly check first (i.e. Does adding this ticket quantity go over a limit? yes/OK add it || no/don't add it) then proceed to the cart.

**Comment by joshfeck** [comment]
Page on my testing site where you can see the issue in action:

https://josh.eventespresso.com/events/brn/

**Comment by sethshoultes** [comment]
@tn3rb can you please take a look?

**Comment by tn3rb** [comment]
setting estimate at easy for the time being, but won't know until this is investigated.
it likely just requires a small tweak somewhere, but finding that spot is the trick
