### ISSUE TITLE
Decaf fixes - Fix '0 items were successfully added for this event.'

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/ee4-mer#29]
## Issue Overview
When adding events to the cart using MER, it now shows

> 0 items were successfully added for this event.
https://monosnap.com/file/h4cRaZfnT8iFajjE7JizynfITOjDIu

This works if I checkout 4.10.13.p so looks like it's from the decaf changes.

## Bug report or feature request?

* [x] Bug

## Steps to Reproduce (for bugs)
Use master branch of MER and you'll need https://github.com/eventespresso/event-espresso-core/tree/BUG/rmv-debug-code for Core (unless it's been merged already).

Add a ticket to the cart and view the modal, it will show as above.

**Comment by Pebblo** [comment]
@tn3rb looks like this is back in the current EE$ core release version, should we push a fix in MER to fix this?

**Comment by tn3rb** [comment]
plz see #31

**Comment by tn3rb** [comment]
@Pebblo 
can you plz test whether #31 fixes this issue for you?
