### ISSUE TITLE
Fix the ticket selector showing 'Add to cart' for events that have an alt registration page set when using MER

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/ee4-mer#4]
From Codebase: https://events.codebasehq.com/projects/event-espresso/tickets/8772

Tony Warwick commented on Tuesday 1st September 2015 at 9:02am
If you set the alt registration page within an event the event list (both /events/ and ESPRESSO_EVENTS) will still continue to display 'Add to Cart' for that event.

Clicking on it shows the spinner but does not actually do anything.

**Comment by joshfeck** [comment]
I can't replicate this issue. It may have been fixed in core later.
