### ISSUE TITLE
Fix MER cart so it doesn't allow adding more tickets to the cart allowed per event per order from the event list

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/ee4-mer#5]
From Codebase: https://events.codebasehq.com/projects/event-espresso/tickets/9450

Tony Warwick commented on Monday 29th February 2016 at 3:46am (edited on 29 Feb 2016 at 10:54am)
Reported here: https://eventespresso.com/topic/max-no-of-tickets-allowed-per-order-for-this-event-with-multi-event-registration/

To reproduce create an event with multiple tickets and set the Max tickets per order to 1.

On the event list page you'll see a radio button for each ticket, like this - http://take.ms/HPR75

Select the first ticket and add it to the cart. You'll get the MER popup and can select what to do, chose to return to event list - http://take.ms/h92wrQ

Now select a different ticket and click 'View Event Cart' - http://take.ms/et3Ml

The page refreshes and you can see the event list again, now do the same for another ticket if you have one - http://take.ms/f11Jg

So now because we have all 3 tickets from this event selected it won't matter which you chose next, but select a ticket you previously 'added' to the cart and click to view the cart - 
http://take.ms/0drS7

You can't use the + button for any ticket, they correctly show the notice - http://take.ms/ojrx8

An error has occurred: You have attempted to purchase 1 ticket but
that would result in too many tickets in the Event Cart for this
event. The registration limit for this event is 1 ticket per
transaction, therefore the total number of tickets you may purchase at
any time can not exceed 1.

I don't think that's expected is it?

Brent Christensen commented on Monday 29th February 2016 at 9:11am
nope.. that's a bug

**Comment by sethshoultes** [comment]
Related to https://github.com/eventespresso/ee4-mer/issues/6

**Comment by joshfeck** [comment]
I cannot replicate this issue.
