### ISSUE TITLE
Add a way to keep track of min/max ticket quantities (bundles) and enforce them in the MER cart

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/ee4-mer#7]
Steps to replicate the issue:

1. Set up a ticket bundle or similar ticket that has a min and or max quantity. You could follow either of the examples from these guides:

https://eventespresso.com/wiki/create-ticket-bundle/

https://eventespresso.com/wiki/set-graduated-ticket-pricing/

2. After setting up the event with the  bundle price ( like 10 tickets at a lower price ), then go to the event page and add that bundle to your cart
<img width="745" alt="Screen Shot 2020-02-21 at 1 36 21 PM" src="https://user-images.githubusercontent.com/891156/75061810-7eb4a780-54af-11ea-89f7-17b12e5f0061.png">

3. then go to view the cart,
4. then set the quantity in the cart to 1; You can use either the text input or the + - inputs
Unexpected result:
You get the bundle price but only buy 1 ticket.
<img width="691" alt="Screen Shot 2020-02-21 at 1 37 29 PM" src="https://user-images.githubusercontent.com/891156/75061871-a3a91a80-54af-11ea-89e8-4f00e17e00b7.png">

The reverse is also possible where you can add more tickets than the max quantity limit for that ticket.

Brent mentioned that a possible solution would be "if a ticket can have a qty between 5 and 10, then we can just disable the buttons when it hits those limits.

It may also require some validation for the text input fields too.

Reported in these topics:

https://eventespresso.com/topic/minimum-and-maximum-quantity-not-respected-on-cart-page/
https://eventespresso.com/topic/bundle-pricing/#post-234433
https://eventespresso.com/topic/buy-one-get-one-free/#post-256166
https://eventespresso.com/topic/minimum-ticket-bug-update-request/

**Comment by tn3rb** [comment]
setting estimate at easy for the time being, but won't know until this is investigated.

**Comment by joshfeck** [comment]
More reports from the forums that apply to this issue:

https://eventespresso.com/topic/customer-can-change-quantity-for-graduated-pricing-other-than-maxmin/

https://eventespresso.com/topic/min-max-ticket-qty/

https://eventespresso.com/topic/minimum-and-maximum-ticket-quantity-bug-in-event-cart/

**Comment by joshfeck** [comment]
See PR #24
